name: FrontEnd Pipeline


on:
  push:
    branches:
      - main
    pull_request:
      branches: [main]    
      types: [opened, synchronize]

jobs:
  frontend_testing:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 
        with:          
          node-version: '20'

      - name: Check directory
        run: |
          cd frontend
          pwd
          ls -l

      - name: Install dependencies
        run: |
          cd frontend
          npm install
        
      - name: Lint code
        run: |
          cd frontend
          npm run lint

      - name: Prettier code
        run: |
          cd frontend
          npm run prettier

      - name: Jest tests
        run: |
          cd frontend
          npm run test

      - name: E2E tests
        run: |
          cd frontend
          npm run dev &
          npm run e2e:run
        env:
          DEV_PROXY_URL: ${{ secrets.PROD_PROXY_URL }}
      
      - name: Build app
        run: |
          cd frontend
          npm run build

  
  frontend_deployment:
    needs: frontend_testing
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Secrets flyctl
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skipfront') }}
        run: |
          cd frontend
          flyctl secrets set PROD_PROXY_URL=$PROD_PROXY_URL
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          PROD_PROXY_URL: ${{ secrets.PROD_PROXY_URL }}
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}

      - name: Deploy flyctl
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skipfront') }}
        run: |
          cd frontend
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          PROD_PROXY_URL: ${{ secrets.PROD_PROXY_URL }}
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}

      - name: Visit app
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skipfront') }}
        run: |
          app_url=${{ secrets.APP_URL }}
          curl -I $app_url
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
